name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          # update the Node version to meet your needs
          node-version: 'latest'
          cache: 'pnpm'

      - name: Build
        run: |
          pnpm i
          pnpm run build
          pnpm run export
          touch out/.nojekyll

      - name: Deploy
        # configure an external GitHub Pages deploy workflow here
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main
          folder: out
