name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          # update the Node version to meet your needs
          node-version: 'latest'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false
      
      - name: Get pnpm store directory
        run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
        id: pnpm-cache
      
      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Build
        run: |
          pnpm i
          pnpm run build
          touch out/.nojekyll

      - name: Deploy
        # configure an external GitHub Pages deploy workflow here
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main
          folder: out
          token: ${{ secrets.GITHUB_TOKEN }}
